// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBswFZg2GRfq9rWOfyevgfPM9_0D_OgNyE',
    appId: '1:279342816690:web:820824f67c402b1d7898ab',
    messagingSenderId: '279342816690',
    projectId: 'payflow-a43c5',
    authDomain: 'payflow-a43c5.firebaseapp.com',
    storageBucket: 'payflow-a43c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpmswKOPHVDd1hpEhQGBjd4AIOF-IcuwU',
    appId: '1:279342816690:android:8f7236abd766d2f77898ab',
    messagingSenderId: '279342816690',
    projectId: 'payflow-a43c5',
    storageBucket: 'payflow-a43c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAOMbnCxjaCLnu9ShgVLZAk8FhtEku16Y',
    appId: '1:279342816690:ios:8bfae7a321856e5e7898ab',
    messagingSenderId: '279342816690',
    projectId: 'payflow-a43c5',
    storageBucket: 'payflow-a43c5.appspot.com',
    androidClientId: '279342816690-dv12vhcdjf1rfhtp6eskt4qf58rkj043.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAOMbnCxjaCLnu9ShgVLZAk8FhtEku16Y',
    appId: '1:279342816690:ios:8bfae7a321856e5e7898ab',
    messagingSenderId: '279342816690',
    projectId: 'payflow-a43c5',
    storageBucket: 'payflow-a43c5.appspot.com',
    androidClientId: '279342816690-dv12vhcdjf1rfhtp6eskt4qf58rkj043.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBswFZg2GRfq9rWOfyevgfPM9_0D_OgNyE',
    appId: '1:279342816690:web:5f950c8628c08e237898ab',
    messagingSenderId: '279342816690',
    projectId: 'payflow-a43c5',
    authDomain: 'payflow-a43c5.firebaseapp.com',
    storageBucket: 'payflow-a43c5.appspot.com',
  );
}
